### PR TITLE
fix persist add store transaction fix #447

### LINKED ISSUE #447: Persist can cause store to get into inconsistent state
Let's say that one is using the sql store. Persist looks like this:

```
func (s *session) persist(seqNum int, msgBytes []byte) error {
        if !s.DisableMessagePersist {
                if err := s.store.SaveMessage(seqNum, msgBytes); err != nil {
                        return err
                }
        }

        return s.store.IncrNextSenderMsgSeqNum()
}
```

So it will save the message to the `messages` table, and after that, update the outgoing seqnum in the `sessions` table.

However if the process is terminated in the middle (or there's a database error), you can end up with the message in the `messages` table, but the outgoing seqnum will still be the old one in the `sessions` table. Ideally there'd be some transactionality here, but the interfaces don't have anything like that.

This causes problems when the process is restarted and tries to send a message. It will insert another message into the `messages` table, which will fail due to a primary key constraint.

I believe a reasonable solution would be to flip those two around. In the failure case outlined, you'll just have burned a seqnum, which seems like a reasonable thing to do in such an exceptional situation.

### PR DESCRIPTION
**Pull request by sami-sweng**

### CODE REVIEW

File: mongostore.go [hunk 1]
```diff
@@ -248,6 +248,15 @@ func (store *mongoStore) SaveMessage(seqNum int, msg []byte) (err error) {
 	return
 }
 
+func (store *mongoStore) SaveMessageAndIncrNextSenderMsgSeqNum(seqNum int, msg []byte) error {
+	// TODO add transaction
```
Comment (ackleymi) [inline mongostore.go:252]: is this TODO still needed?

**Comment by ackleymi** [comment]
I like this change a lot so far, I'm just hesitant to merge it without a unit test proving that it solves #447

**Comment by ackleymi** [comment]
Merging into a wip branch for now, want to test this for myself, will reopen PR into main after

**Comment by ackleymi** [comment]
https://github.com/quickfixgo/quickfix/pull/528
